### ISSUE TITLE
Move message and status bar to be above the migrate button

### ISSUE THREAD

**Issue by mposk** [SimeonGriggs/sanity-plugin-migration#1]
For larger migrations, users need to scroll back to the top of the payload list to see the status. It would be nice to have the display right above the button.

example:
![image](https://user-images.githubusercontent.com/50845834/126195554-2cd76ca9-8f0a-4c20-aeb7-a76374f5aef1.png)

**Comment by SimeonGriggs** [comment]
The latest version makes the top section "sticky" so that the target/destination, message and progress bar should always be in view.
