### ISSUE TITLE
Strange issue with the datasets label

### ISSUE THREAD

**Issue by DMA-tio** [SimeonGriggs/sanity-plugin-migration#2]
![image](https://user-images.githubusercontent.com/39726979/157397833-3ce13edc-b32c-4b66-885e-fa6e6d394222.png)
The label for each dataset seems to be displayed the other way around, when migrating, everything works as it should, it looks like it's just a visual thing.

**Comment by SimeonGriggs** [comment]
Which version are you using? I just pushed changes last week (`0.1.3`) ideally to resolve this.

**Comment by DMA-tio** [comment]
Hi Simon, you're right what i had done previously was to just `sanity upgrade`, now i've re-installed via npm and now it works fine, Thank you for your swift response
